name: test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: source.vim
        run: echo "TODO: soruce test/source.vim in vim by cli"
